name: Analyze utPLSQL

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'utPLSQL/utPLSQL'

      - uses: felipebz/zpa-cli-action@main
